# Generated by Django 4.2.7 on 2023-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
